<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL1kpTYL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL1kpTYL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL1kpTYL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL1kpTYL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL1kpTYL\App_KernelDevDebugContainer([
    'container.build_hash' => 'L1kpTYL',
    'container.build_id' => 'bf803b9a',
    'container.build_time' => 1587063244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL1kpTYL');
